### ISSUE TITLE
No support for MESSAGE_STORE_SETTINGS_PATH

### ISSUE THREAD

**Issue by jheinnic** [eventide-project/message-store-postgres-database#9]
When using the quickstart project, https://github.com/eventide-examples/quickstart, the README.md file contains a section that instructs the user to set database connectivity properties in `settings/message_store_postgtres.json`.

The very next section then instructs the user to use a script from this project to create the database:

```
bundle exec evt-pg-create-db
```

But none of the scripts in this project seem to be in any way aware of `settings/message_store_postgres.json` or the enviornment variable that can be used to provide an alternate location to the `message-store-postgres` gem's ruby code, `MESSAGE_STORE_SETTINGS_PATH`.

I'm attempting to explore the bootstrap with a Dockerized instance of postgres, exposed through a non-standard port in order to isolate that exploration from my locally installed Postgresql instance running outside of Docker on port 5432.

I was able to work around this by juggling instance availability, but if the database I was connecting to were not running on my same host, I'd have to resort to something like binding an SSH channel to port 5432 on localhost to the correct port on the other end of an SSH tunnel to the correct host.

It's going to make proposing considering Eventide to my coworkers with such a stilted initial development experience.

If you would be interested in a PR submission to help improve the situation, any recommendations about how you would prefer to get the information from the JSON file to the appropriate command line arguments would be helpful.  I'd imagine you might want to define a shell function in some utils.sh bundle that gets sourced and results in an environment variable like PSQL_OPTIONS getting set for interpolation into each psql (or createdb call).

My only pause about that is that this project seems to constrain itself to shell scripting and AFAIK that precludes any built-in facility for JSON parsing/extraction.  There are of course programs and interpreters that can be installed to do that task, but I'd want to solicit feedback about what would constitute an acceptable dependency for doing this, or would it be necessary to use tools like grep and awk to extract the relevant information using a non-JSON-aware approach?

**Comment by sbellware** [comment]
@jheinnic Indeed, the setup is geared toward to most common denominator in systems operations tooling, which is inevitably shell scripting. And that's ultimately why the message store database operations scripts require nothing more than a shell, and are not bound to any more higher-order tools beyond the `psql` tool.

The basic workflow for message database operations presumes that whatever tools are provided with the message store will fit into existing workflows for database operations.

Conversely, the JSON settings file is for the runtime configuration of a database connection from applicative code (rather than operations tooling).

Here's a link to the mention in the documentation about using an environment variable to specify the name of the database being created: http://docs.eventide-project.org/user-guide/message-store/tools.html#use-an-alternate-database-name.

The name of the database to be created (etc) is the limit of what can be controlled with the `evt-pg-*` command line tools. And it should be affirmed here that those tools are really intended for use by developers on their own developer machines where Postgres is installed alongside all of the other basic and minimum developer tools (even though they can be used on operational servers, if so desired).

It's expected that the tools provided by PostreSQL itself are both sufficient and preferable for database and server operations, and that's why we don't try to supplant them or re-implement them.

Note: The only thing that will be "dirtied" by installing the message store database in your local, dev machine Postgres server is the `message_store` role (Postgres roles are server-wide). Everything else about the message store is self-contained within the message_store database.

All that said, Postgres provides some pretty straight-forward ways out-of-the-box to connect to and control a database other than the local dev database.

The Postgres Password File is probably the most basic approach:
https://www.postgresql.org/docs/current/libpq-pgpass.html

The Postgres Connection Service File is another alternative:
https://www.postgresql.org/docs/current/libpq-pgservice.html

In the end, these are Postgres concerns more than they are Eventide concerns, and we defer to Postgres' tooling whenever we can in order to not conflict or contradict the things that are already being done by Postgres operators.

So, I'm not sure that a PR is in order. The message store database is also being used by teams who word in Go and teams who work in Node. At this level of the stack, there's more value in _not_ binding to more Ruby that absolutely necessary.

That said, I can imagine a tool _built on top of_ the message store library that does things the way that your issue description suggests. But I don't see it as something that would necessarily be part of the message store library itself. 

Also, sorry for the late reply. Things are a bit busy these days, but that's no excuse. You should have received an acknowledgement a lot quicker than this 5-day delay.

You'll get a lot quicker response from the Eventide Slack org, namely the `usage` channel. If you feel like you can tolerate yet-another Slack org in your life, here's a signup link: https://eventide-project-slack.herokuapp.com/

But no pressure to join the Slack. I'm happy to keep the dialog going right here.
